# Generated by Django 5.1.5 on 2025-05-23 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de entrenamiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora del entrenamiento')),
                ('location', models.CharField(max_length=50, verbose_name='Dirección lugar de entrenamiento')),
                ('phone', models.CharField(max_length=20, verbose_name='Celular del cliente')),
                ('notes', models.CharField(max_length=150, verbose_name='Comentarios adicionales')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('training_type', models.ManyToManyField(to='cronograma.trainingtype')),
            ],
            options={
                'verbose_name_plural': 'Sesiones de entrenamiento',
                'ordering': ['date'],
            },
        ),
    ]
