# Generated by Django 5.1.5 on 2025-06-24 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingAppointment',
            new_name='TrainingReservation',
        ),
        migrations.AlterModelOptions(
            name='trainingreservation',
            options={'ordering': ['date'], 'verbose_name': 'Reserva de entrenamiento', 'verbose_name_plural': 'Reservas de entrenamiento'},
        ),
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de entrenamiento', 'verbose_name_plural': 'Tipos de entrenamiento'},
        ),
    ]
