# Generated by Django 5.1.5 on 2025-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_rename_trainingappointment_trainingreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_type_images/', verbose_name='Imagen'),
        ),
    ]
