# Generated by Django 5.1.5 on 2025-07-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0003_trainingtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingreservation',
            name='training_type',
        ),
        migrations.AddField(
            model_name='trainingreservation',
            name='training_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronograma.trainingtype'),
        ),
    ]
