# Generated by Django 5.1.5 on 2025-07-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0004_remove_trainingreservation_training_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreservation',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
