# Generated by Django 5.1.5 on 2025-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0005_trainingreservation_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingreservation',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentarios adicionales'),
        ),
    ]
